title:
  archive: Archive
  category: Category
  tag: Tag

menu:
  home: Home
  archives: Archives
  categories: Categories
  tags: Tags
  about: About
  search: Search

sidebar:
  overview: Overview
  toc: Table Of Contents

post:
  sticky: Sticky
  posted: Posted on
  in: In
  read_more: Read more
  untitled: Untitled
  toc_empty: This post does not have a Table Of Contents

page:
  totally: Totally
  tags: tags

footer:
  powered: "Powered by %s"
  theme: Theme

counter:
  tag_cloud:
    zero: No tags
    one: Tag
    other: "Tags"

  categories:
    zero: No categories
    one: Category
    other: "Categories"

  archive_posts:
    zero: No posts.
    one: 1 post.
    other: "%d archived posts in total."

state:
  posts: posts
  pages: pages
  tags: tags
  categories: categories

cheers:
  um: Um..
  ok: OK
  nice: Nice
  good: Good
  great: Great
  excellent: Excellent

keep_on: takeradi's busy typing. His typing speed sucks!

symbol:
  comma: ', '
  period: '. '
